/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles.index'
import { Route as VehiclesSlugRouteImport } from './routes/vehicles.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesSlugRoute = VehiclesSlugRouteImport.update({
  id: '/vehicles/$slug',
  path: '/vehicles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vehicles/$slug': typeof VehiclesSlugRoute
  '/vehicles/': typeof VehiclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vehicles/$slug': typeof VehiclesSlugRoute
  '/vehicles': typeof VehiclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vehicles/$slug': typeof VehiclesSlugRoute
  '/vehicles/': typeof VehiclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/applications'
    | '/contact'
    | '/sitemap.xml'
    | '/vehicles/$slug'
    | '/vehicles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/applications'
    | '/contact'
    | '/sitemap.xml'
    | '/vehicles/$slug'
    | '/vehicles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/applications'
    | '/contact'
    | '/sitemap.xml'
    | '/vehicles/$slug'
    | '/vehicles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplicationsRoute: typeof ApplicationsRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VehiclesSlugRoute: typeof VehiclesSlugRoute
  VehiclesIndexRoute: typeof VehiclesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$slug': {
      id: '/vehicles/$slug'
      path: '/vehicles/$slug'
      fullPath: '/vehicles/$slug'
      preLoaderRoute: typeof VehiclesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplicationsRoute: ApplicationsRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VehiclesSlugRoute: VehiclesSlugRoute,
  VehiclesIndexRoute: VehiclesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
